apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: django-gitops
  namespace: argocd

spec:
  project: default

  spec:
  source:
    repoURL: https://github.com/mrcaption49/KubernetesGitOpsArgoCD.git
    targetRevision: master
    path: django-k8s-demo/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true